/**
 * Pure geometry + scroll-timeline math for `ProjectsShowreel.tsx` — a
 * scroll-driven "camera flight" through a scattered 3D field of project
 * tiles, inspired by the user-supplied "AI Studio" reference template's
 * Projects/Showreel section (`ai-studio/src/utils/showreel/{geometry,
 * timeline}.ts`, `ai-studio/src/views/home/showreel-stage.tsx`) — adapted,
 * not copied: that reference drives a multi-scene hero→carousel→sphere→
 * portfolio journey with per-tile progress-driven transforms; this is a
 * single, much smaller flight-through-a-grid moment scoped to what the
 * Projects page actually needs, built from scratch with this project's own
 * numbers and written fresh in this codebase's own idiom (see
 * `ProjectsShowreel.tsx` for why the animated pieces are just two values —
 * a camera-rig transform and a group opacity — rather than a per-tile
 * timeline).
 *
 * Tiles render each project's real photo (`project.image`, see
 * `data/mocks/projects.ts`'s own header for provenance — no per-project
 * photography could be scraped from the live site, ADR-0065/ADR-0071, but
 * real photos were supplied directly and mapped in ADR-0073). Layout
 * (position/depth/rotation/size) is still generated by the seeded PRNG
 * below so the grid reads as an organic collage rather than a rigid grid.
 */
import type { Project } from "@/data/mocks/projects";

export interface ShowreelTile {
  project: Project;
  x: number;
  y: number;
  z: number;
  rotateY: number;
  width: number;
  height: number;
}

const clamp01 = (x: number): number => Math.min(1, Math.max(0, x));

/** Deterministic PRNG (mulberry32) — tile layout must be stable across
 * re-renders and between server/client, so `Math.random()` (reseeded every
 * call) is not an option here. */
const mulberry32 = (seed: number): (() => number) => {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
};

const COLS = 6;
const CELL_W = 340;
const CELL_H = 260;
const JITTER = 70;
const DEPTH_LAYERS = [-420, -220, -60, 120, 320];

/** Scatters every real project into a wide, depth-varied 3D field —
 * computed once (memoised by the caller), not per frame. */
export const buildShowreelTiles = (projects: Project[]): ShowreelTile[] => {
  const rows = Math.ceil(projects.length / COLS);
  const originX = ((COLS - 1) * CELL_W) / 2;
  const originY = ((rows - 1) * CELL_H) / 2;

  return projects.map((project, i) => {
    const rand = mulberry32(i * 2654435761 + 1);
    const col = i % COLS;
    const row = Math.floor(i / COLS);
    const jitterX = (rand() - 0.5) * JITTER;
    const jitterY = (rand() - 0.5) * JITTER;
    const z = DEPTH_LAYERS[i % DEPTH_LAYERS.length] + (rand() - 0.5) * 60;
    const scale = 0.85 + rand() * 0.4;

    return {
      project,
      x: col * CELL_W - originX + jitterX,
      y: row * CELL_H - originY + jitterY,
      z,
      rotateY: (rand() - 0.5) * 22,
      width: Math.round(CELL_W * 0.62 * scale),
      height: Math.round(CELL_H * 0.72 * scale),
    };
  });
};

export const tileTransform = (tile: ShowreelTile): string =>
  `translate3d(${tile.x}px, ${tile.y}px, ${tile.z}px) rotateY(${tile.rotateY.toFixed(2)}deg)`;

/** How much scroll (vh) the whole flight takes. */
export const TRACK_VH = 260;

/**
 * The one animated "camera" transform — scaling the whole tile field up and
 * pushing it toward the viewer reads as flying through the collage; every
 * tile's OWN transform (`tileTransform` above) is static, so the parallax
 * falls naturally out of CSS 3D perspective rather than a per-tile formula.
 */
export const cameraRigTransform = (p: number): string => {
  const t = clamp01(p);
  const eased = t * t * (3 - 2 * t);
  const scale = 1 + eased * 4.4;
  const tz = eased * 900;
  const rx = eased * -6;
  return `translate3d(0px, 0px, ${tz.toFixed(1)}px) scale(${scale.toFixed(3)}) rotateX(${rx.toFixed(2)}deg)`;
};

/** Fades the field in over the first 8% of the track and out over the last
 * 18% — clearing the stage for the CTA/heading beneath it. */
export const gridOpacity = (p: number): number => {
  const t = clamp01(p);
  const fadeIn = clamp01(t / 0.08);
  const fadeOut = 1 - clamp01((t - 0.82) / 0.18);
  return Math.min(fadeIn, fadeOut);
};

/** The intro eyebrow/heading — visible only at the very top of the track. */
export const introOpacity = (p: number): number => 1 - clamp01(clamp01(p) / 0.1);

/** The "explore all projects" cue — revealed as the flight settles. */
export const ctaOpacity = (p: number): number => clamp01((clamp01(p) - 0.83) / 0.14);
