import Link from "next/link";
import { GeotechnicalPlexusScene } from "@/components/scene/GeotechnicalPlexusScene";
import { Inview } from "@/components/animation/springs/in-view";
import { Magnetic } from "@/components/common/Magnetic";
import { GeotechnicalPlexusHeading } from "./GeotechnicalPlexusHeading";

/**
 * Homepage feature section for the Geotechnical Plexus scene — see
 * `build-geotechnical-plexus-scene.ts` for the 3D implementation and its
 * architecture notes. A Server Component: only the leaves that need hooks
 * (`GeotechnicalPlexusHeading`, `Inview`, `GeotechnicalPlexusScene`) are
 * client, matching `home/HeroSection.tsx`'s own composition pattern.
 *
 * Still built on the shared `-engineering` token set (see globals.css) —
 * that palette is also `/services/geotechnical-engineering`'s own hero
 * background (`GeotechnicalAnalysisHero.tsx`), which must stay its original
 * light "engineering diagram" look. Rather than touch the shared Tier-2
 * defaults (which would repaint that page too), this section overrides
 * `--surface-engineering`/`--ink-engineering`/`--ink-engineering-muted` on
 * its own `<section>` via Tailwind's arbitrary-property syntax — the
 * page-scoped Tier-2 override pattern design-system.md documents for
 * `--accent`. It works here because every consumer below is a genuine
 * Tailwind utility (`bg-surface-engineering`, `text-ink-engineering`, …)
 * generated by `@theme inline`, which resolves its `var()` live at each
 * element rather than freezing it — a hand-written CSS rule referencing the
 * Tier-3 alias directly would NOT pick this up (see design-system.md's
 * ADR-0059 warning). `--accent-engineering` (the button) is deliberately
 * left un-overridden — the teal stays.
 */
export const GeotechnicalPlexusSection = () => {
  return (
    <section
      id="digital-twin"
      aria-labelledby="geotechnical-plexus-heading"
      className="bg-surface-engineering [--ink-engineering-muted:var(--raw-color-white)] [--ink-engineering:var(--raw-color-white)] [--surface-engineering:var(--raw-color-navy-925)] relative overflow-hidden py-20 md:py-28"
    >
      <div className="relative z-10 mx-auto grid w-full max-w-7xl grid-cols-1 items-center gap-12 px-6 lg:grid-cols-[1fr_1.2fr] lg:gap-16 md:px-8">
        <div>
          <Inview
            tag="p"
            mode="once"
            from={{ opacity: 0, y: 16 }}
            to={{ opacity: 1, y: 0 }}
            className="text-ink-engineering mb-4 text-xs tracking-[0.3em] uppercase"
          >
            Digital Twin · Ground Intelligence
          </Inview>

          <GeotechnicalPlexusHeading
            id="geotechnical-plexus-heading"
            text="See beneath every site before you build on it"
            className="text-ink-engineering leading-display max-w-xl text-3xl font-medium md:text-5xl"
          />

          <Inview
            tag="p"
            mode="once"
            from={{ opacity: 0, y: 16 }}
            to={{ opacity: 1, y: 0 }}
            delayIn={100}
            className="text-ink-engineering-muted mt-6 max-w-md text-lg"
          >
            Every stratum, borehole and pile modelled together — the same ground data our engineers use to validate a foundation before the first shovel turns. Scroll to see the strata separate, then reassemble.
          </Inview>

          <Inview
            tag="div"
            mode="once"
            from={{ opacity: 0, y: 16 }}
            to={{ opacity: 1, y: 0 }}
            delayIn={180}
            className="mt-10"
          >
            <Magnetic>
              <Link
                href="/services/geotechnical-engineering"
                className="bg-accent-engineering hover:bg-accent-engineering/90 transition-colors duration-[var(--duration-fast)] ease-entrance inline-flex items-center rounded-full px-8 py-4 text-sm font-medium tracking-[0.08em] text-white uppercase"
              >
                Explore Geotechnical Engineering
              </Link>
            </Magnetic>
          </Inview>
        </div>

        <div
          className="border-line-engineering relative h-[420px] w-full overflow-hidden rounded-2xl border md:h-[560px]"
          data-cursor="canvas"
        >
          <GeotechnicalPlexusScene className="h-full w-full" />
        </div>
      </div>
    </section>
  );
};
